### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by AyeMinnKyaw29** [NezitX/better-snippets#1]
If I created a new snippet. And I will use it.
I found a cursor error. 
Eg: If I type p that I created, and I clicked enter

it will happen like this <p></p>| 
that cursor is the end of the p tag. 
I want there to be the cursor between the tag.
like this <p>|</p>

https://github.com/user-attachments/assets/db32d783-89dd-4ca1-aa19-46f47b394961

**Comment by NezitX** [comment]
Sorry for late response,

you can make the curser between the tags by putting `${1}`. e.g.:

```snippets
<p>${1}</p>
```
for more information about snippets read [this](https://cloud9-sdk.readme.io/docs/snippets)
